version: '3.7'
services:
    site-client:
        container_name: next:latest
        build:
            context: frontend
            dockerfile: Dockerfile
        ports:
            - 80:3000
        restart: always
        networks: 
            - frontend
    
    site-server: 
        container_name: backend:latest
        build: 
            context: ../PersonalWebsiteBE/backend
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        restart: always
        environment: 
            spring_profiles_active: prod
        networks: 
            - backend
            - frontend
networks: 
    backend:
    frontend:
